apiVersion: v1
data:
  database-name: c2FtcGxlZGI=
  database-password: TXhYMXBmeXNxZkJhbVdXUQ==
  database-root-password: VEZuSXBIb2JTS2g4WEhjcA==
  database-user: dXNlclJRSw==
kind: Secret
metadata:
  annotations:
    template.openshift.io/expose-database_name: '{.data[''database-name'']}'
    template.openshift.io/expose-password: '{.data[''database-password'']}'
    template.openshift.io/expose-root_password: '{.data[''database-root-password'']}'
    template.openshift.io/expose-username: '{.data[''database-user'']}'
  name: mysql
  labels:
    app: mariadb
    template: mariadb
type: Opaque